@startuml
!theme materia
[*] --> Ожидание_начала_игры

Ожидание_начала_игры --> Раздача_карт : Игроки делают ставки
Раздача_карт --> Игровой_процесс : Карты разданы

state Игровой_процесс {
    [*] --> Ожидание_хода_игрока

    Ожидание_хода_игрока --> Ожидание_хода_игрока : Хит
    Ожидание_хода_игрока --> Ожидание_хода_игрока : Дабл
    Ожидание_хода_игрока --> Ожидание_хода_игрока : Сплит
    Ожидание_хода_игрока --> Ожидание_следующего_игрока : Стоп

    Ожидание_следующего_игрока --> Ожидание_хода_игрока : Следующий игрок
    Ожидание_следующего_игрока --> Ход_дилера : Все игроки завершили ходы
}

Ход_дилера --> Определение_результата : Дилер завершил ход

Определение_результата --> Ожидание_начала_игры : Результаты определены

@enduml
